################################################################################
# Appveyor-CI
# -----------
#
################################################################################

# Setup
################################################################################

version: "{build}"

branches:
  except:
    - prototype/.*
    - gh-pages

# Agents
################################################################################

os:
  - Visual Studio 2015
  - Visual Studio 2017

# Jobs
################################################################################

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

# Stages
################################################################################

install:
  - cmd: .\.appveyor\install.cmd

before_build:
  - set CXXFLAGS="/permissive- /std:c++latest"
  - cmd: .\.appveyor\before-build.cmd

build:
  project: build\Expected.sln
  parallel: true
  verbosity: normal

test_script:
  - cmd: .\.appveyor\test.cmd
