name: Deploy Conan

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deployment Agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan --version

      - name: Prepare Conan Environment
        run: |
          conan remote add bintray ${{ secrets.BINTRAY_REMOTE_URL }}
          conan user -p ${{ secrets.BINTRAY_API_KEY }} -r bintray ${{ secrets.BINTRAY_USERNAME }}
          version=$(conan inspect $(pwd) --attribute version | sed 's@version: @@g')
          echo "CONAN_PACKAGE_PATH=Result/${version}@result/stable" >> $GITHUB_ENV

      - name: Package
        run: |
          conan create . "result/stable"

      - name: Test Package
        run: |
          conan test $(pwd)/.conan/test_package "${CONAN_PACKAGE_PATH}"

      - name: Deploy
        run: |
          conan upload "${CONAN_PACKAGE_PATH}" -r bintray --all
